### PR TITLE
Connection details for remoties

### PR DESCRIPTION
**Pull request by lsblakk**
I put this up in Yammer and people are confused by the current instructions on how to get this up and running by themselves.  I hope this might help non webdev folks have an instance up in their home offices.  Took out the stuff about changing the location tag since that seems to be hit or miss on my end, it's very opaque and the average new user will not need it for now.  I'm happy to try and write more documentation for it to flesh out the intended usage.

### CODE REVIEW

**Comment by mythmon** [comment]
It seems weird that the 3 commands for the web console are all on one line now, instead of 3 separate lines. Is that a point of confusion for people? Besides that, I like these changes, they make things much clearer, thanks!

**Comment by mpurzynski** [comment]
How should the location tag look like? I've tried something like this:

config.name = "sos1"; config.tags = ["ambient", "whimsy"]; writeConfig();

And got in response:

undefined
Object { raw: "http://whattrainisitnow.com/ screen=ambient11", _args: Array[0], screen: Array[1], url: "http://whattrainisitnow.com/", type: "url" } app.js:40
"You receive a message, but it's not for you..."

I can see google trends, which look cool but not exactly what I'm looking for ;-)

**Comment by lsblakk** [comment]
I thought it would be clearer to people if they just did it all on one line, but that's just my opinion - not stuck on doing it that way.

**Comment by wagnerand** [comment]
So, location is one of ```settings::timer.screens```?

**Comment by mythmon** [comment]
`config.name` can be anything. It is used sometimes to refer to a particular screen, like in `settings::timer.screens`.  We generally name things with the location they are in, and a number, like `pdx-ambient1`, but that's not required. Just make sure to be unique.

The messages you got are actually what would be expected. the `undefined` was the result of `writeConfig()`, and the message after that was just one of the other messages flowing through the system.

Google trends is one of the things in the whimsy tag in state.json, so it is also expected that you would see that.

**Comment by mythmon** [comment]
@lsblakk I'm not too picky about one line vs multiple lines, but it might be good to incorporate some of @wagnerand's questions into this. Do you want to tackle that, or should we merge this as is?

**Comment by mpurzynski** [comment]
Thanks, everything is clear now! :-)

**Pull request merged**
