### PR TITLE
update sfo tag in state.json

### PR DESCRIPTION
**Pull request by jlin**
Add SFO zoom transition timeline slides to sfo tag.

### CODE REVIEW

**Comment by jlin** [comment]
hmm not sure why the ci didn't succeed. Is it the trailing comma at the end of my line?

**Comment by emceeaich** [comment]
Most likely.

**Comment by jlin** [comment]
yay it passed! confirmed that it was the trailing comma.

**Comment by jlin** [comment]
Hi @emceeaich can you help me commit this now that it's passing the tests?

**Comment by marksagrouch** [comment]
Could we get this this pull request merged please?

**Pull request merged**
