### PR TITLE
Everything is fine

### PR DESCRIPTION
**Pull request by lsblakk**
An addition to whimsy.

### CODE REVIEW

**Comment by lonnen** [comment]
I like it, I really do, but I suspect the face melting is a bit much for regular rotation. Could you crop it to just the first row?

**Comment by lsblakk** [comment]
updated the image on people - see if it works for you better now.

**Comment by lonnen** [comment]
YISS

**Comment by lonnen** [comment]
thanks lukas!

**Comment by dolske** [comment]
\o/

**Pull request merged**
