### PR TITLE
Show trailhead video

### PR DESCRIPTION
**Pull request by emceeaich**

### CODE REVIEW

**Comment by mythmon** [comment]
It seems we have a bug on Corsica right now that prevents video from auto playing, so this just doesn't work. Also, that video has a lot of motion for a general ambient display.

Could we switch to a gif version, and maybe something lower-motion or static?

**Comment by emceeaich** [comment]
Let's do the gif for the day and replace with a static image after today.

**Comment by mythmon** [comment]
This doesn't look very good on the screen; it doesn't scale up and only takes up about 1/4 of the screen. I think we need to host this somewhere that sends proper mime types, so that corsica-image can do its thing. I usually use imgur.

The animation also loops awkwardly, and isn't smooth. I think it looks bad, and we should just use the static one starting today.

**Comment by mythmon** [comment]
Alternatively, if we could modify the gif to play once and then stop, that would look pretty good IMO. I'm not sure how to do that off hand though. I'm pretty sure we would need to modify the image itself.

**Comment by emceeaich** [comment]
I switched this to use a background image, I agree running it once would be better

Or just replace it with the static image

**Comment by emceeaich** [comment]
I'll replace this with the static tomorrow.

**Pull request merged**
