### PR TITLE
add tpe-lab tag and content for Hasal team

### PR DESCRIPTION
**Pull request by MarkYan**
Hi~ I'm Mark, a student worker in Mozilla Taipei Office. I am working in Hasal team, which conducts some speed testing on Firefox and Chrome.

I created some web pages as the dashboard to present our team's testing progress. We would like to combine those pages into your system. Therefore, we can display the content with your project on the TV in our Taipei lab.

### CODE REVIEW

**Comment by MarkYan** [comment]
@potch r?
Would you help review this patch?

**Comment by potch** [comment]
@MarkYan This looks pretty good! I assume there are specific TVs this applies to?

**Comment by MarkYan** [comment]
Hi~ @potch, We have TVs, which we are now playing single web page on them to show our daily running progress, in Hasal's lab at Mozilla Taipei office. We plan to display more web pages with moz-corsica on those TVs.

**Comment by MarkYan** [comment]
Hi ~ @potch could you help merge this patch if it is okay. Therefore, we will be able to display with this project on our TVs. Thanks a lot. ^^

**Comment by potch** [comment]
@MarkYan done! Sorry for the delay, let me know if you need anything else.

**Pull request merged**
