### PR TITLE
Adding a link to Aurora and Beta uplifts dashboard

### PR DESCRIPTION
**Pull request by rkothari19**
Adding a link to Aurora and Beta uplifts dashboard

### CODE REVIEW

**Comment by potch** [comment]
I tested this out, and don't see any data on the dashboard. Any tips on getting it configured and working?

**Comment by rkothari19** [comment]
The first load is a bit low but subsequent loads should be better as the browser caching helps.

**Comment by lonnen** [comment]
It's pretty difficult to read. The legends especially. There is a lot of wasted space on the right. Consider four single graphs and displaying one randomly?

**Comment by klahnakoski** [comment]
Got it!   I will fix the centering, and maybe add a random parameter

**Comment by lonnen** [comment]
It's been a few months without an update so I'm going to close this. Please reopen or open anew if you make additional updates.

**Pull request closed without merging**
