### PR TITLE
add in strava stats

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by mythmon** [comment]
This looks a little out of place on the TVs. Is it possible to make it responsive so it fills the screen better? Viewport units (`vw`, `vh`, `vmin`, and `vmax`) are really useful for this. The screens are all 16:9, if that helps.

img_20170801_094538

The links at the bottom aren't usable on the TVs either, since they aren't interactive. It might be good to replace them with raw URLs or some other way to find the groups and github repo.

**Comment by andymckay** [comment]
Oh wow that looked so cool on my laptop and so not cool there. I'll play around.

**Comment by andymckay** [comment]
@mythmon could you see if that looks better please?

**Comment by mythmon** [comment]
Here's a screenshot from the responsive design tools set to 1080p. Looks pretty good to me. One small nit is the wrapping of the last line, but I think this is good enough to merge.

screen shot 2017-08-03 at 10 25 33

**Comment by andymckay** [comment]
Cool thanks, next to add in some funky graphs... :)

**Pull request merged**
