### PR TITLE
Add links to tree pushes/backouts

### PR DESCRIPTION
**Pull request by AutomatedTester**
This shows pushes and backouts against inbound and fx-team

### CODE REVIEW

**Comment by potch** [comment]
@AutomatedTester It looks like the graphs are rendered at a fixed size. Is there any chance you can make them take up the viewport instead? Corsica dashboards need to render well on a few different sized screens.

**Comment by potch** [comment]
The graph sizing looks much better, though you may want to subtract some fixed value from the graph width/height so the page doesn't overflow.

Other notes from when I tried it out in front of an audience in the kitchen:
* Bars are a bit narrow, making hour-to-hour comparison a bit tricky
* Pushes / Backouts are swapped on the two legends, and the captializations aren't consistent.

So just a few nits, but this is pretty much ready to go!

**Comment by AutomatedTester** [comment]
@potch 
I think I have addressed all comments

**Comment by potch** [comment]
needed manual merge, closed in dda989e.

**Pull request closed without merging**
