### PR TITLE
remove mozilla-strava, seems a bit broken

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by mythmon** [comment]
What seems broken about it to you? It looks fine on the mozpdx screens here.

**Comment by andymckay** [comment]
The numbers weren't matching what Strava was showing, it could have been a strava error. I just haven't had time to revist the script yet.

**Comment by mythmon** [comment]
Ah, ok. I was only looking at the visuals of the page, not the data itself.

**Comment by andymckay** [comment]
Thanks @mythmon

**Pull request merged**
