### PR TITLE
update corsica, forever to latest versions

### PR DESCRIPTION
**Pull request by lonnen**
this gets us onto the latest version of corsica, and updates the forever library

### CODE REVIEW

**Comment by mythmon** [comment]
Where did Corsica 2.6 come from? https://github.com/mozilla/corsica/blob/master/package.json#L3 lists 2.5.

**Comment by lonnen** [comment]
Well this is fun:

```
$ npm search corsica
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
corsica                   | Ephemeral screens…   | =potch…         | 2021-02-17 | 2.6.0    |
```

**Comment by lonnen** [comment]
I took the version number of NPM for writing this patch. NPM differs from the main repo because Potch has been manually updating NPM with the latest, and in this instance he incremented the version number and published to NPM without updating the main repository.

So fun!

`mozilla/corsica` is up to date now with the correct version number. I've diffed master against the npm artifact and that version number was the only change. This should all be reconciled now.

**Comment by lonnen** [comment]
side note - I updated issue 78 on the main repo to address the publishing problem https://github.com/mozilla/corsica/issues/78

**Comment by mythmon** [comment]
Ah, that makes sense. Thanks for tracking that down.

**Pull request merged**
