### PR TITLE
Add privacy-not-included banner

### PR DESCRIPTION
**Pull request by jlin**
Add to ambient tag the Holiday Buyers Guide

Let me know if the slides are ok for inclusion. Thanks!

### CODE REVIEW

**Comment by mythmon** [comment]
I'd recommend a few changes here:

* Since this is already a static image, we should skip the Google Slides deck and serve the image directly. We can host these images [directly in this repository](https://github.com/mozilla/moz-corsica/tree/master/images)
* We should not use the animated version. We tend to avoid motion on the ambient displays.
* The image is a resolution of 1600x900. This will work but isn't ideal. Most of the ambient displays are 1920x1080. If we can get a higher resolution image, it will look better on the screen.

**Comment by jlin** [comment]
Thanks, I've passed on the feedback and will get a higher res image for the static image.

**Comment by jlin** [comment]
Hi mythmon, I have the new file ready. I'm assuming I include the file with this pull request, but how do I refer to it via url? would it be some form of https://raw.githubusercontent.com/mozilla/moz-corsica/master/images/filename.jpg ?

**Comment by mythmon** [comment]
Yes, I believe that should work. I'll also verify it once we get things going.

**Comment by mythmon** [comment]
This looks good, thanks for the updates!

**Comment by jlin** [comment]
Great! Thanks for the help! I see it in the TOR ambients!

**Pull request merged**
