### PR TITLE
add FFX CampaignMeter static image

### PR DESCRIPTION
**Pull request by jlin**
update state.json - add FFX CampaignMeter static image - working with Chelsea Novak to put up weekly stats of our campaign.

Hi Moz-Corsica maintainers! We have a new graphic for the FFx Campaign currently running! Let me know if you have questions. It's a static image for inclusion into the ambient displays running moz-corsica.

Thanks!
Jonathan

### CODE REVIEW

**Comment by mythmon** [comment]
The Travis CI build failed because your new file is not valid JSON. You need a comma on the end of the line.

**Comment by jlin** [comment]
ahhhh sorry let me retry this. I'm using the github editor - did that fix it?

**Comment by mythmon** [comment]
Yep, that did it. This is good to go now.

**Comment by jlin** [comment]
Thanks very much!

**Pull request merged**
