### PR TITLE
Update Berlin office slides

### PR DESCRIPTION
**Pull request by georgf**
- Adding gslide for Berlin office events.
- Removing tupperware amnesty. No more amnesty, back to judgemental
stares!

### CODE REVIEW

**Comment by georgf** [comment]
Side-question: What happens if referenced gslides have more than one slide? Is one picked randomly?

**Comment by potch** [comment]
@georgf yes, one is picked randomly each time that source comes up.

**Comment by georgf** [comment]
Great, ok.
That question wasn't blocking review/merge anyway, so this is good to go :)

**Comment by georgf** [comment]
@emceeaich, would you be able to take a look?

**Pull request merged**
