### PR TITLE
add berlin-sccache dashboard to berlin corsica

### PR DESCRIPTION
**Pull request by mozfreddyb**

### CODE REVIEW

**Comment by mythmon** [comment]
Have you tested this on the Corsica displays in Berlin? At least here in Portland, the dashboard is not accessible from the machines running the Corsica screens.

**Comment by mozfreddyb** [comment]
I haven't tested, but assumed it was possible because the displays are in the "office network".
Are they connected to the guest network?

**Comment by mozfreddyb** [comment]
Feel free to close this if my assumption was wrong :)

**Comment by mythmon** [comment]
I'm not sure about the Berlin set up. Here in Portland the displays are connected to the guest network, and so don't have special access. Testing via [the Corsica REPL](https://github.com/potch/corsica-repl) would be a good idea.

Also, if you would prefer, we could merge this change and then if there are problems (which would be very easy to spot), we could back it out.

**Comment by mozfreddyb** [comment]
@wagnerand Do you know which network our Berlin corisca screen is connected to?

**Comment by wagnerand** [comment]
I asked Riccardo to clarify.

**Comment by mythmon** [comment]
A relic from the before time. Surely we don't need this anymore.

**Pull request closed without merging**
